GET http://localhost:3000/books

### create a book
POST http://localhost:3000/books
Content-Type: application/json

{
    "title": "Rich Dad, Poor Dad",
    "author": "Robert T kiosaki",
    "summary": "Finance management book"
}

### Get a single book
GET http://localhost:3000/books/654b8e1f24ffce486c58b79d

### Update a single book
PATCH  http://localhost:3000/books/654b8e1f24ffce486c58b79ds
Content-Type: application/json

{
    "title":"Rich Dad, Poor Dad",
    "author":"Robert sir",
    "summary":"How to manage your money"
}

### Delete a single book
DELETE  http://localhost:3000/books/654b8cffd95972b0e86a218f


### Invalid
GET  http://localhost:3000/
 